apiVersion: v1
kind: Pod
metadata:
  name: curriculum-pod
spec:
  containers:
  - name: curriculum-container
    image: <image-name>
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: curriculum-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: curriculum-volume
    configMap:
      name: curriculum-configmap
